# Generated by Django 4.2.6 on 2023-12-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstApplication', '0003_remove_challenge_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_type',
            new_name='description',
        ),
    ]
